server:
  port: 8084


eureka:
  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，本身就是所有无需注册
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://admin:admin@127.0.0.1:8083/eureka/

Spring:
  security:
    user: #配置用户的账号信息
      name: admin
      password: admin